from .core import ProjectionInputs


def make_inputs(
    start_weight,
    start_bf,
    training_quality,
    base_bulk_weeks,
    base_cut_weeks,
    surplus,
    deficit,
    total_weeks,
    scale_coeff,
    start_mode,
    first_phase_weeks,
    training_status,
    protein_g_per_kg,
    activity_level,
    measured_maintenance_kcal,
    fixed_intake,
    cycle_strategy,
    bulk_stop_body_fat_pct,
    cut_stop_body_fat_pct,
    minimum_phase_weeks,
    finish_lean,
):
    return ProjectionInputs(
        float(start_weight),
        float(start_bf),
        float(training_quality),
        training_status,
        float(protein_g_per_kg),
        float(base_bulk_weeks),
        float(base_cut_weeks),
        int(surplus),
        int(deficit),
        float(total_weeks),
        float(scale_coeff),
        start_mode,
        float(first_phase_weeks),
        activity_level,
        float(measured_maintenance_kcal) if measured_maintenance_kcal is not None else None,
        bool(fixed_intake),
        cycle_strategy,
        float(bulk_stop_body_fat_pct),
        float(cut_stop_body_fat_pct),
        float(minimum_phase_weeks),
        bool(finish_lean),
    )
